CREATE FILE FORMAT IF NOT EXISTS FACTOR_MODEL_PROJECT.RAW.CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE IF NOT EXISTS FACTOR_MODEL_PROJECT.RAW.CSV_STAGE
    FILE_FORMAT = FACTOR_MODEL_PROJECT.RAW.CSV_FORMAT;

COPY INTO FACTOR_MODEL_PROJECT.RAW.RETURNS (
    DATE, WORLD_EQUITIES, US_TREASURIES_10YR, HIGH_YIELD, INFLATION_PROTECTION,
    CURRENCY_PROTECTION, US_EQUITY, SP500_TOTAL_RETURN, SP500, INTERNATIONAL_EQUITY,
    US_TREASURY_20YR, CORPORATE_BOND, REAL_ESTATE, COMMODITY, TIPS
)
FROM @FACTOR_MODEL_PROJECT.RAW.CSV_STAGE/returns.csv;

COPY INTO FACTOR_MODEL_PROJECT.RAW.FACTOR_LOOKUP (
    FACTOR_NAME, FACTOR_CATEGORY, FACTOR_SHORT_DESCRIPTION
)
FROM @FACTOR_MODEL_PROJECT.RAW.CSV_STAGE/factor_lookup.csv;
