-- 03_load_data.sql
-- TODO: replace this TEMPLATE with the COPY INTO commands you actually ran.
-- (Snowsight: Query history shows the exact statements. Also check
--  SHOW STAGES; and SHOW FILE FORMATS; for the names you used.)
--
-- Tip: use SKIP_HEADER = 1 so the CSV header row is not loaded as data.

-- CREATE FILE FORMAT IF NOT EXISTS FACTOR_MODEL_PROJECT.RAW.CSV_FORMAT
--     TYPE = CSV
--     SKIP_HEADER = 1
--     FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- COPY INTO FACTOR_MODEL_PROJECT.RAW.RETURNS (
--     DATE, WORLD_EQUITIES, US_TREASURIES_10YR, HIGH_YIELD, INFLATION_PROTECTION,
--     CURRENCY_PROTECTION, US_EQUITY, SP500_TOTAL_RETURN, SP500, INTERNATIONAL_EQUITY,
--     US_TREASURY_20YR, CORPORATE_BOND, REAL_ESTATE, COMMODITY, TIPS
-- )
-- FROM @<your_stage>/<returns_file>.csv
-- FILE_FORMAT = (FORMAT_NAME = 'FACTOR_MODEL_PROJECT.RAW.CSV_FORMAT');

-- COPY INTO FACTOR_MODEL_PROJECT.RAW.FACTOR_LOOKUP (
--     FACTOR_NAME, FACTOR_CATEGORY, FACTOR_SHORT_DESCRIPTION
-- )
-- FROM @<your_stage>/<lookup_file>.csv
-- FILE_FORMAT = (FORMAT_NAME = 'FACTOR_MODEL_PROJECT.RAW.CSV_FORMAT');
